#!/usr/bin/env python3
"""
STATUS: REAL — Master Auto-Detection & Startup Orchestrator
ASIMNEXUS Zero-Configuration Prototype Launcher
==================================================
Scans hardware capabilities, checks for local models, auto-configures ports,
sets up environment variables, installs dependencies, and launches both backend
and frontend concurrently.
"""

import os
import sys
import time
import socket
import subprocess
import webbrowser
import platform
import shutil
from pathlib import Path

# Color configuration for terminal output
class Colors:
    GREEN = '\033[92m'
    RED = '\033[91m'
    YELLOW = '\033[93m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    BOLD = '\033[1m'
    END = '\033[0m'

def log(msg, level="info"):
    timestamp = time.strftime("%H:%M:%S")
    prefix = {
        "success": f"{Colors.GREEN}[✓] {Colors.END}",
        "error": f"{Colors.RED}[✗] {Colors.END}",
        "warning": f"{Colors.YELLOW}[!] {Colors.END}",
        "header": f"\n{Colors.CYAN}{Colors.BOLD}=== ",
        "info": f"{Colors.BLUE}[i] {Colors.END}"
    }
    
    if level == "header":
        print(f"{prefix[level]}{msg} ==={Colors.END}")
    else:
        print(f"[{timestamp}] {prefix[level]}{msg}")

def check_port_free(port):
    """Check if a local port is free."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        try:
            s.bind(("127.0.0.1", port))
            return True
        except socket.error:
            return False

def find_next_free_port(start_port, max_tries=100):
    """Scan and find the first available port."""
    for port in range(start_port, start_port + max_tries):
        if check_port_free(port):
            return port
    raise RuntimeError(f"Could not find any free port starting from {start_port}")

def detect_hardware():
    """Detect OS, CPU, RAM and GPU capabilities to optimize local LLM runtime."""
    log("Scanning device hardware capabilities...", "header")
    system = platform.system()
    machine = platform.machine()
    cpu_cores = os.cpu_count() or 4
    log(f"OS: {system} ({machine})")
    log(f"CPU Cores: {cpu_cores}")
    
    gpu_type = "CPU"
    gpu_layers = 0
    threads = max(1, cpu_cores - 2)
    
    # Check for NVIDIA CUDA
    if shutil.which("nvidia-smi"):
        try:
            res = subprocess.run(["nvidia-smi"], capture_output=True, text=True)
            if res.returncode == 0:
                gpu_type = "NVIDIA CUDA GPU"
                gpu_layers = 30 # Offload more layers to GPU
                log("NVIDIA GPU detected via nvidia-smi.", "success")
        except Exception:
            pass
            
    # Check for Apple Silicon (Metal/MPS support)
    elif system == "Darwin" and machine in ("arm64", "aarch64"):
        gpu_type = "Apple Silicon GPU (Metal)"
        gpu_layers = 35 # Metal handles GGUF very well
        log("Apple Silicon detected (Metal acceleration enabled).", "success")
        
    log(f"Optimization suggestion: Running on {gpu_type} with {threads} CPU threads and {gpu_layers} GPU layers offloaded.")
    return {"gpu_layers": gpu_layers, "threads": threads, "system": system}

def find_local_model():
    """Scan for local GGUF models in common locations."""
    log("Scanning for local GGUF model files...", "header")
    models_dir = Path("models")
    workspace_dir = Path(".")
    
    # 1. Check default models folder
    if models_dir.exists():
        gguf_files = list(models_dir.glob("*.gguf"))
        if gguf_files:
            log(f"Found GGUF model: {gguf_files[0].name}", "success")
            return gguf_files[0]
            
    # 2. Check whole workspace
    gguf_files = list(workspace_dir.glob("**/*.gguf"))
    if gguf_files:
        log(f"Found GGUF model in workspace: {gguf_files[0]}", "success")
        return gguf_files[0]
        
    log("No local GGUF model file found (.gguf). Using fallback mock inference.", "warning")
    return None

def setup_environment(backend_port, frontend_port, model_path, hardware):
    """Dynamically write .env files for both backend and frontend."""
    log("Configuring environment settings...", "header")
    
    # Root .env configuration
    env_content = f"""# Auto-generated by ASIMNEXUS Auto-Launcher
ASIM_JWT_SECRET=1bbda42817ff20dd6aa87731522f58e81279aec684d61212484f7b73eea0aa19
ASIM_ALLOWED_ORIGINS=http://localhost:{frontend_port},http://localhost:{backend_port}
ASIM_DB_PATH=data/asim_core.db
ASIM_DATA_DIR=data
ASIM_LOG_LEVEL=INFO
ASIM_RELEASE_CHANNEL=stable
ASIM_HOST=127.0.0.1
ASIM_PORT={backend_port}
REACT_APP_API_URL=http://localhost:{backend_port}
"""
    if model_path:
        env_content += f"ASIM_LOCAL_MODEL_PATH={model_path.resolve()}\n"
        
    with open(".env", "w", encoding="utf-8") as f:
        f.write(env_content)
    log("Updated root .env successfully.")
    
    # Frontend react .env configuration
    react_env_dir = Path("frontend/react")
    if react_env_dir.exists():
        react_env_content = f"REACT_APP_API_URL=http://localhost:{backend_port}\nPORT={frontend_port}\n"
        with open(react_env_dir / ".env", "w", encoding="utf-8") as f:
            f.write(react_env_content)
        log("Updated frontend/react/.env with correct API url and port.")

def install_dependencies():
    """Verify and install any missing pip/npm dependencies."""
    log("Verifying backend python dependencies...", "header")
    try:
        import fastapi
        import uvicorn
        log("FastAPI and Uvicorn already installed.")
    except ImportError:
        log("Installing missing python dependencies from requirements.txt...", "warning")
        subprocess.run([sys.executable, "-m", "pip", "install", "-r", "requirements.txt"])
        
    log("Verifying frontend node modules...", "header")
    node_modules_dir = Path("frontend/react/node_modules")
    if not node_modules_dir.exists():
        log("node_modules not found. Running npm install...", "warning")
        npm_cmd = "npm.cmd" if platform.system() == "Windows" else "npm"
        try:
            subprocess.run([npm_cmd, "install"], cwd="frontend/react")
            log("Frontend dependencies installed successfully.", "success")
        except Exception as e:
            log(f"Could not run npm install: {e}. Please install node/npm manually.", "error")

def run_services(backend_port, frontend_port):
    """Launch the backend and frontend processes concurrently."""
    log("Launching AsimNexus Services...", "header")
    
    # Start Backend
    log(f"Starting Backend on port {backend_port}...")
    backend_env = os.environ.copy()
    backend_env["ASIM_PORT"] = str(backend_port)
    backend_proc = subprocess.Popen(
        [sys.executable, "simple_backend.py", "--port", str(backend_port)],
        env=backend_env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1
    )
    
    # Wait for backend to be online
    backend_ready = False
    for i in range(15):
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                s.connect(("127.0.0.1", backend_port))
                backend_ready = True
                break
        except socket.error:
            time.sleep(1)
            
    if backend_ready:
        log(f"Backend is online at http://localhost:{backend_port}", "success")
    else:
        log("Backend failed to start in time. Check stdout.", "error")
        
    # Start Frontend
    log(f"Starting Frontend on port {frontend_port}...")
    npm_cmd = "npm.cmd" if platform.system() == "Windows" else "npm"
    frontend_env = os.environ.copy()
    frontend_env["PORT"] = str(frontend_port)
    frontend_env["REACT_APP_API_URL"] = f"http://localhost:{backend_port}"
    
    frontend_proc = subprocess.Popen(
        [npm_cmd, "start"],
        cwd="frontend/react",
        env=frontend_env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True
    )
    
    # Automatically open browser
    log("Opening browser to frontend dashboard...", "info")
    time.sleep(3)
    webbrowser.open(f"http://localhost:{frontend_port}")
    
    log("AsimNexus complete system running successfully!", "success")
    log("Press Ctrl+C to terminate both servers.", "warning")
    
    try:
        # Keep monitoring backend and print output
        while True:
            line = backend_proc.stdout.readline()
            if line:
                print(f"{Colors.CYAN}[Backend]{Colors.END} {line.strip()}")
            if backend_proc.poll() is not None:
                log("Backend stopped unexpectedly.", "error")
                break
            time.sleep(0.01)
    except KeyboardInterrupt:
        log("Shutting down services...", "warning")
    finally:
        backend_proc.terminate()
        frontend_proc.terminate()
        log("AsimNexus services stopped.", "success")

def main():
    log("ASIMNEXUS AUTO-DETECTION & LAUNCHER", "header")
    
    # 1. Detect ports
    backend_port = find_next_free_port(8000)
    frontend_port = find_next_free_port(3000)
    log(f"Determined Free Ports -> Backend: {backend_port} | Frontend: {frontend_port}")
    
    # 2. Hardware scan
    hardware = detect_hardware()
    
    # 3. Model detection
    model_path = find_local_model()
    
    # 4. Dependency verify
    install_dependencies()
    
    # 5. Environment configuration
    setup_environment(backend_port, frontend_port, model_path, hardware)
    
    # 6. Start complete system
    run_services(backend_port, frontend_port)

if __name__ == "__main__":
    main()
