"""
Mirror Module Routes
====================
REST API for the Mirror Module — digital twin reflection, contradiction detection,
evolution suggestions, and daily reporting.

Reference:
  - core/mirror/mirror_module.py — Core MirrorModule implementation
  - core/mirror/consciousness.py — ConsciousnessLayer and Thought types
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Body, HTTPException, Query

from routes.response import ok, error

logger = logging.getLogger("AsimNexus.Routes.Mirror")

router = APIRouter(tags=["Mirror"])

# Module-level globals (set via init_mirror)
orchestrator = None


def init_mirror(app_globals: dict) -> None:
    """Initialize mirror module with shared app state."""
    global orchestrator
    orchestrator = app_globals.get("orchestrator")


# ─── Reflection ──────────────────────────────────────────────────────────────


@router.post("/api/mirror/reflect")
async def mirror_reflect(data: dict = Body(...)):
    """Reflect on an action and generate a mirror reflection.

    Request body:
      - user_id (str, required): The user performing the action
      - action (dict, required): The action to reflect on
        - intent (str): The intent of the action
        - details (dict): Additional action details
      - user_type (str, optional): User type (default: "citizen")

    Returns:
      - reflection: The generated MirrorReflection with analysis
    """
    try:
        from core.mirror import get_mirror

        user_id = data.get("user_id")
        action = data.get("action")
        user_type = data.get("user_type", "citizen")

        if not user_id or not action:
            return error("user_id and action are required")

        mirror = get_mirror(user_id, user_type)
        reflection = await mirror.reflect(action)

        return ok(data={
            "reflection_id": reflection.reflection_id,
            "user_id": reflection.user_id,
            "intent": reflection.intent,
            "contradictions": reflection.contradictions,
            "balance_impact": reflection.balance_impact,
            "response": reflection.response,
            "timestamp": reflection.timestamp,
        })
    except Exception as e:
        logger.exception("Failed to reflect on action")
        return error(str(e))


@router.get("/api/mirror/reflections")
async def mirror_reflections(
    user_id: str = Query(..., description="User ID"),
    limit: int = Query(50, description="Max reflections to return"),
):
    """Get recent mirror reflections for a user.

    Query params:
      - user_id (str, required): The user ID
      - limit (int, optional): Max reflections (default: 50)

    Returns:
      - reflections: List of recent MirrorReflection objects
    """
    try:
        from core.mirror import get_mirror

        mirror = get_mirror(user_id)
        report = mirror.get_daily_report()
        reflections = report.get("recent_reflections", [])[:limit]

        return ok(data={
            "user_id": user_id,
            "reflections": reflections,
            "count": len(reflections),
        })
    except Exception as e:
        logger.exception("Failed to get reflections")
        return error(str(e))


# ─── Contradictions ──────────────────────────────────────────────────────────


@router.get("/api/mirror/contradictions")
async def mirror_contradictions(
    user_id: str = Query(..., description="User ID"),
):
    """Get detected contradiction patterns for a user.

    Query params:
      - user_id (str, required): The user ID

    Returns:
      - contradictions: List of contradiction patterns
      - contradiction_rate: Current contradiction rate
    """
    try:
        from core.mirror import get_mirror

        mirror = get_mirror(user_id)
        patterns = mirror._analyze_contradiction_patterns()
        rate = mirror._get_contradiction_rate()

        return ok(data={
            "user_id": user_id,
            "contradiction_rate": rate,
            "patterns": patterns,
            "requires_review": mirror.requires_human_review(),
        })
    except Exception as e:
        logger.exception("Failed to get contradictions")
        return error(str(e))


# ─── Evolution Suggestions ───────────────────────────────────────────────────


@router.get("/api/mirror/evolution-suggestions")
async def mirror_evolution_suggestions(
    user_id: str = Query(..., description="User ID"),
    suggestion_type: Optional[str] = Query(None, description="Filter by suggestion type"),
):
    """Get evolution suggestions generated by the mirror.

    Query params:
      - user_id (str, required): The user ID
      - suggestion_type (str, optional): Filter by suggestion type

    Returns:
      - suggestions: List of EvolutionSuggestion objects
    """
    try:
        from core.mirror import get_mirror

        mirror = get_mirror(user_id)
        suggestions = mirror.get_evolution_suggestions(suggestion_type=suggestion_type)

        return ok(data={
            "user_id": user_id,
            "suggestions": [s.to_dict() if hasattr(s, "to_dict") else s for s in suggestions],
            "count": len(suggestions),
        })
    except Exception as e:
        logger.exception("Failed to get evolution suggestions")
        return error(str(e))


@router.post("/api/mirror/evolution-suggestions/{suggestion_id}/apply")
async def mirror_apply_suggestion(
    suggestion_id: str,
    user_id: str = Body(..., embed=True),
):
    """Apply an evolution suggestion.

    Path params:
      - suggestion_id (str, required): The suggestion ID

    Request body:
      - user_id (str, required): The user ID

    Returns:
      - applied: Whether the suggestion was applied successfully
    """
    try:
        from core.mirror import get_mirror

        mirror = get_mirror(user_id)
        applied = mirror.apply_suggestion(suggestion_id)

        if not applied:
            return error("Suggestion not found or already applied")

        return ok(data={"suggestion_id": suggestion_id, "applied": True})
    except Exception as e:
        logger.exception("Failed to apply suggestion")
        return error(str(e))


# ─── Daily Report ────────────────────────────────────────────────────────────


@router.get("/api/mirror/daily-report")
async def mirror_daily_report(
    user_id: str = Query(..., description="User ID"),
):
    """Get the daily mirror report for a user.

    Query params:
      - user_id (str, required): The user ID

    Returns:
      - report: Full daily report with analytics
    """
    try:
        from core.mirror import get_mirror

        mirror = get_mirror(user_id)
        report = mirror.get_daily_report()

        return ok(data=report)
    except Exception as e:
        logger.exception("Failed to get daily report")
        return error(str(e))


# ─── Nightly Dream / Evolution ──────────────────────────────────────────────


@router.post("/api/mirror/nightly-dream")
async def mirror_nightly_dream(
    user_id: str = Body(..., embed=True),
    user_type: str = Body("citizen", embed=True),
):
    """Trigger a nightly dream cycle for evolution suggestions.

    Request body:
      - user_id (str, required): The user ID
      - user_type (str, optional): User type (default: "citizen")

    Returns:
      - suggestions: List of generated EvolutionSuggestion objects
    """
    try:
        from core.mirror import get_mirror

        mirror = get_mirror(user_id, user_type)
        suggestions = await mirror.nightly_dream()

        return ok(data={
            "user_id": user_id,
            "suggestions": [s.to_dict() if hasattr(s, "to_dict") else s for s in suggestions],
            "count": len(suggestions),
        })
    except Exception as e:
        logger.exception("Failed to run nightly dream")
        return error(str(e))


# ─── Consciousness ───────────────────────────────────────────────────────────


@router.get("/api/mirror/consciousness")
async def mirror_consciousness(
    user_id: str = Query("system", description="User ID"),
):
    """Get the current state of the consciousness layer.

    Query params:
      - user_id (str, optional): User ID (default: "system")

    Returns:
      - consciousness: Current consciousness state with thoughts and principles
    """
    try:
        from core.mirror.consciousness import ConsciousnessLayer

        consciousness = ConsciousnessLayer(user_id=user_id)
        state = consciousness.get_state()

        return ok(data=state)
    except Exception as e:
        logger.exception("Failed to get consciousness state")
        return error(str(e))


@router.post("/api/mirror/consciousness/thought")
async def mirror_add_thought(data: dict = Body(...)):
    """Add a thought to the consciousness layer.

    Request body:
      - user_id (str, optional): User ID (default: "system")
      - thought_type (str, required): Type of thought
      - content (str, required): Thought content
      - source (str, optional): Source of the thought

    Returns:
      - thought: The created Thought object
    """
    try:
        from core.mirror.consciousness import ConsciousnessLayer, Thought, ThoughtType

        user_id = data.get("user_id", "system")
        thought_type_str = data.get("thought_type")
        content = data.get("content")
        source = data.get("source", "api")

        if not thought_type_str or not content:
            return error("thought_type and content are required")

        try:
            thought_type = ThoughtType(thought_type_str)
        except ValueError:
            valid_types = [t.value for t in ThoughtType]
            return error(f"Invalid thought_type. Valid: {valid_types}")

        consciousness = ConsciousnessLayer(user_id=user_id)
        thought = Thought(
            thought_type=thought_type,
            content=content,
        )
        consciousness.add_thought(thought)

        return ok(data={
            "thought_id": thought.thought_id,
            "thought_type": thought.thought_type.value,
            "content": thought.content,
            "source": thought.source,
            "timestamp": thought.timestamp,
        })
    except Exception as e:
        logger.exception("Failed to add thought")
        return error(str(e))


# ─── Auto Fine-Tune ──────────────────────────────────────────────────────────


@router.post("/api/mirror/auto-fine-tune")
async def mirror_auto_fine_tune(
    user_id: str = Body(..., embed=True),
):
    """Trigger auto fine-tuning of the mirror model.

    Request body:
      - user_id (str, required): The user ID

    Returns:
      - result: Fine-tuning result with metrics
    """
    try:
        from core.mirror import get_mirror

        mirror = get_mirror(user_id)
        result = await mirror.auto_fine_tune()

        return ok(data=result)
    except Exception as e:
        logger.exception("Failed to auto fine-tune")
        return error(str(e))
