
"""
STATUS: PARTIAL — Auto-labeled by batch_label.py
"""

"""
ASIMNEXUS API Key Migration Script
===================================

This script migrates API keys from api_keys.json to .env file
for secure environment variable management.

Usage:
    python scripts/migrate_keys_to_env.py

This will:
1. Read api_keys.json
2. Extract all API keys
3. Create/update .env file with proper formatting
4. Add .env to .gitignore if not present
"""

import json
import os
import sys
from pathlib import Path


def migrate_keys():
    """Migrate API keys from JSON to .env"""
    
    # Paths
    base_dir = Path(__file__).parent.parent
    api_keys_path = base_dir / "data" / "api_keys.json"
    env_path = base_dir / ".env"
    gitignore_path = base_dir / ".gitignore"
    
    print(f"📁 Base directory: {base_dir}")
    
    # Check if api_keys.json exists
    if not api_keys_path.exists():
        print(f"❌ api_keys.json not found at {api_keys_path}")
        return False
    
    # Load api_keys.json
    with open(api_keys_path, 'r') as f:
        data = json.load(f)
    
    api_keys = data.get('api_keys', {})
    print(f"🔑 Found {len(api_keys)} API keys to migrate")
    
    # Read existing .env or create new
    env_content = {}
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_content[key] = value
        print(f"📄 Loaded existing .env with {len(env_content)} variables")
    
    # Map JSON keys to env variables
    key_mapping = {
        'openai_1': 'OPENAI_API_KEY',
        'anthropic_1': 'ANTHROPIC_API_KEY',
        'gemini_1': 'GEMINI_API_KEY',
        'gemini_2': 'GEMINI_2_API_KEY',
        'grok_1': 'GROK_API_KEY',
        'grok_2': 'GROK_2_API_KEY',
        'gemma_1': 'GEMMA_1_API_KEY',
        'gemma_2': 'GEMMA_2_API_KEY',
        'gemma_3': 'GEMMA_3_API_KEY',
        'gemma_4': 'GEMMA_4_API_KEY',
        'newsapi_1': 'NEWSAPI_KEY',
        'coingecko_1': 'COINGECKO_API_KEY',
        'github_1': 'GITHUB_TOKEN',
        'cloudinary_1': 'CLOUDINARY_URL',
        'pollinations_1': 'POLLINATIONS_KEY',
        'mongodb_1': 'MONGODB_URI',
        'supabase_1': 'SUPABASE_KEY',
    }
    
    # Add NVIDIA NIM keys (1-24)
    for i in range(1, 25):
        key_mapping[f'nvidia_nim_{i}'] = f'NVIDIA_NIM_{i}_KEY'
    
    # Migrate keys
    migrated_count = 0
    for json_key, env_var in key_mapping.items():
        if json_key in api_keys:
            api_data = api_keys[json_key]
            api_key = api_data.get('api_key', '')
            if api_key and api_key != f'your_{json_key}_here':
                env_content[env_var] = api_key
                migrated_count += 1
                print(f"  ✅ Migrated {json_key} -> {env_var}")
    
    # Add Supabase URL separately
    if 'supabase_1' in api_keys:
        supabase_data = api_keys['supabase_1']
        base_url = supabase_data.get('base_url', '')
        if base_url:
            env_content['SUPABASE_URL'] = base_url
            print(f"  ✅ Migrated supabase URL")
    
    # Add NVIDIA base URL
    if 'nvidia_nim_1' in api_keys:
        nvidia_data = api_keys['nvidia_nim_1']
        base_url = nvidia_data.get('base_url', '')
        if base_url:
            env_content['NVIDIA_BASE_URL'] = base_url
            print(f"  ✅ Migrated NVIDIA base URL")
    
    # Write .env file
    with open(env_path, 'w') as f:
        f.write("# ASIMNEXUS Environment Configuration\n")
        f.write("# Generated by migrate_keys_to_env.py\n\n")
        
        # Group by category
        categories = {
            'LLM': ['OPENAI', 'ANTHROPIC', 'GEMINI', 'GROK', 'GEMMA', 'NVIDIA'],
            'SERVICES': ['NEWSAPI', 'COINGECKO', 'GITHUB', 'CLOUDINARY', 'POLLINATIONS'],
            'DATABASE': ['SUPABASE', 'MONGODB', 'REDIS', 'POSTGRES'],
        }
        
        # Write LLM keys first
        f.write("# ============================================\n")
        f.write("# LLM API Keys\n")
        f.write("# ============================================\n")
        for key, value in sorted(env_content.items()):
            if any(llm in key for llm in ['OPENAI', 'ANTHROPIC', 'GEMINI', 'GROK', 'GEMMA', 'NVIDIA']):
                f.write(f"{key}={value}\n")
        
        f.write("\n# ============================================\n")
        f.write("# Service API Keys\n")
        f.write("# ============================================\n")
        for key, value in sorted(env_content.items()):
            if any(svc in key for svc in ['NEWSAPI', 'COINGECKO', 'GITHUB', 'CLOUDINARY', 'POLLINATIONS']):
                f.write(f"{key}={value}\n")
        
        f.write("\n# ============================================\n")
        f.write("# Database Configuration\n")
        f.write("# ============================================\n")
        for key, value in sorted(env_content.items()):
            if any(db in key for db in ['SUPABASE', 'MONGODB', 'REDIS', 'POSTGRES', 'PINECONE']):
                f.write(f"{key}={value}\n")
        
        # Write remaining keys
        written_keys = set()
        for section in categories.values():
            for prefix in section:
                for key in env_content:
                    if prefix in key:
                        written_keys.add(key)
        
        remaining = set(env_content.keys()) - written_keys
        if remaining:
            f.write("\n# ============================================\n")
            f.write("# Other Configuration\n")
            f.write("# ============================================\n")
            for key in sorted(remaining):
                f.write(f"{key}={env_content[key]}\n")
    
    print(f"\n✅ Successfully migrated {migrated_count} API keys to .env")
    print(f"📄 .env file created at: {env_path}")
    
    # Update .gitignore
    if gitignore_path.exists():
        with open(gitignore_path, 'r') as f:
            gitignore_content = f.read()
        
        if '.env' not in gitignore_content:
            with open(gitignore_path, 'a') as f:
                f.write("\n# Environment variables\n.env\n")
            print("📝 Added .env to .gitignore")
        else:
            print("📝 .env already in .gitignore")
    else:
        # Create .gitignore
        with open(gitignore_path, 'w') as f:
            f.write("# Environment variables\n.env\n")
            f.write("data/api_keys.json\n")
            f.write("__pycache__/\n")
            f.write("*.pyc\n")
            f.write("*.log\n")
            f.write("node_modules/\n")
        print("📝 Created .gitignore with .env protection")
    
    print("\n⚠️  IMPORTANT: Keep your .env file secret!")
    print("   Never commit it to version control.")
    
    return True


if __name__ == "__main__":
    success = migrate_keys()
    sys.exit(0 if success else 1)
