apiVersion: v1
kind: Service
metadata:
  name: asimnexus-api-service
  namespace: asimnexus
  labels:
    app: asimnexus-api
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: cloud-brain
  selector:
    app: asimnexus-api
